CATEGORIES = [("3D Printing", "3D Printing", ""),
              ("3D Printer Accessories", "3D Printer Accessories", ""),
              ("3D Printer Extruders", "3D Printer Extruders", ""),
              ("3D Printer Parts", "3D Printer Parts", ""),
              ("3D Printer Tests", "3D Printer Tests", ""),
              ("3D Printers", "3D Printers", ""),
              ("Art", "Art", ""),
              ("2D Art", "2D Art", ""),
              ("Art Tools", "Art Tools", ""),
              ("Coins & Badges", "Coins & Badges", ""),
              ("Interactive Art", "Interactive Art", ""),
              ("Math Art", "Math Art", ""),
              ("Scans & Replicas", "Scans & Replicas", ""),
              ("Sculptures", "Sculptures", ""),
              ("Signs & Logos", "Signs & Logos", ""),
              ("Fashion", "Fashion", ""),
              ("Accessories", "Accessories", ""),
              ("Bracelets", "Bracelets", ""),
              ("Costume", "Costume", ""),
              ("Earrings", "Earrings", ""),
              ("Glasses", "Glasses", ""),
              ("Jewelry", "Jewelry", ""),
              ("Keychains", "Keychains", ""),
              ("Rings", "Rings", ""),
              ("Gadgets", "Gadgets", ""),
              ("Audio", "Audio", ""),
              ("Camera", "Camera", ""),
              ("Computer", "Computer", ""),
              ("Mobile Phone", "Mobile Phone", ""),
              ("Tablet", "Tablet", ""),
              ("Video Games", "Video Games", ""),
              ("Hobby", "Hobby", ""),
              ("Automotive", "Automotive", ""),
              ("DIY", "DIY", ""),
              ("Electronics", "Electronics", ""),
              ("Music", "Music", ""),
              ("RC Vehicles", "RC Vehicles", ""),
              ("Robotics", "Robotics", ""),
              ("Sport & Outdoors", "Sport & Outdoors", ""),
              ("Household", "Household", ""),
              ("Bathroom", "Bathroom", ""),
              ("Containers", "Containers", ""),
              ("Decor", "Decor", ""),
              ("Household Supplies", "Household Supplies", ""),
              ("Office", "Office", ""),
              ("Organization", "Organization", ""),
              ("Outdoor & Garden", "Outdoor & Garden", ""),
              ("Pets", "Pets", ""),
              ("Replacement Parts", "Replacement Parts", ""),
              ("Kitchen & Dining", "Kitchen & Dining", ""),
              ("Learning", "Learning", ""),
              ("Biology", "Biology", ""),
              ("Engineering", "Engineering", ""),
              ("Math", "Math", ""),
              ("Physics & Astronomy", "Physics & Astronomy", ""),
              ("Models", "Models", ""),
              ("Animals", "Animals", ""),
              ("Buildings & Structures", "Buildings & Structures", ""),
              ("Creatures", "Creatures", ""),
              ("Food & Drink", "Food & Drink", ""),
              ("Model Furniture", "Model Furniture", ""),
              ("Model Robots", "Model Robots", ""),
              ("People", "People", ""),
              ("Props", "Props", ""),
              ("Vehicles", "Vehicles", ""),
              ("Tools", "Tools", ""),
              ("Hand Tools", "Hand Tools", ""),
              ("Machine Tools", "Machine Tools", ""),
              ("Parts", "Parts", ""),
              ("Tool Holders & Boxed", "Tool Holders & Boxed", ""),
              ("Toys & Games", "Toys & Games", ""),
              ("Chess", "Chess", ""),
              ("Construction Toys", "Construction Toys", ""),
              ("Dice", "Dice", ""),
              ("Games", "Games", ""),
              ("Mechanical Toys", "Mechanical Toys", ""),
              ("Playsets", "Playsets", ""),
              ("Puzzles", "Puzzles", ""),
              ("Toy & Game Accessories", "Toy & Game Accessories", "")]

LICENSES = [("cc-sa", "Creative Commons - Attribution - Share Alike", ""),
            ("cc", "Creative Commons - Attribution",""),
            ("cc-nc", "Creative Commons - Attribution - Non-Commercial", ""),
            ("cc-nc-sa", "Attribution - Non-Commercial - Share Alike", ""),
            ("pd0", "Creative Commons - Public Domain Dedication", ""),
            ("pd", "Public Domain", ""),
            ("gpl", "GNU - GPL", ""),
            ("lgpl", "GNU - LGPL", ""),
            ("bsd", "BSD License", "")]